### ISSUE TITLE
header.date returns incorrect datetime value

### ISSUE THREAD

**Issue by WilliamWalker** [grantbrown/laspy#26]
I have found that header.date returns a datetime value one day in advance of what is actually recorded in the LAS header, regardless of leap year or not.

**Comment by grantbrown** [comment]
Interesting, I'll check this out over the weekend. For a particular file, can you check to see whether:

    inFile.reader.get_header_property("created_day") 
    inFile.reader.get_header_property("created_year")

return reasonable values?

**Comment by WilliamWalker** [comment]
Yes, these return correct values.

**Comment by grantbrown** [comment]
Good catch. Looking back at the code now, I'm not sure why we were worrying about leap years - the datetime library handles them without issues (in any case, the leap year detection seems to have been incorrect).

I believe the changes in [c2ee90](https://github.com/grantbrown/laspy/commit/c2ee90cf5ded5989ee5facf522f13e31ee1fed1d) should address the issue. Let me know if you continue to have problems.
