### ISSUE TITLE
Reading LAS file on a mapped network folder

### ISSUE THREAD

**Issue by kalbermattenm** [grantbrown/laspy#35]
Hi,

I am not sure that this is the best place for my question... but I do not know if this is some kind of bug, or if I misunderstood something (or missed something). I am simply trying to open some LAS files...

I am using Python 2.7.10 32-bits on Windows 7.

If they are on the local disk of my computer, then it works perfectly. If the LAS files are on an external (or mapped) folder, then it does not work...

Here is a simple example using the same file twice:

Python code:

```python
from laspy import file
import os

print "Read a local file:"
tile = 'C:/11234421073.las'

tile_exists = os.path.isfile(tile)

print tile_exists

file_ = file.File(tile, mode = 'r')

print type(file_)
print "Done"

print "Read an external file:"
tile = 'F:/11234421073.las'

tile_exists = os.path.isfile(tile)

print tile_exists

file_ = file.File(tile, mode = 'r')

print type(file_)
```

Output:
```
Read a local file:
True
<class 'laspy.file.File'>
Done
Read an external file:
True
Traceback (most recent call last):
  File "test_las_open.py", line 23, in <module>
    file_ = file.File(tile, mode = 'r')
  File "C:\travail\tmp\las\lib\site-packages\laspy\file.py", line 62, in __init__
    self.open()
  File "C:\travail\tmp\las\lib\site-packages\laspy\file.py", line 73, in open
    self._reader = base.Reader(self.filename,mode= self._mode)
  File "C:\travail\tmp\las\lib\site-packages\laspy\base.py", line 153, in __init__
    self.setup_read_write(vlrs, evlrs)
  File "C:\travail\tmp\las\lib\site-packages\laspy\base.py", line 163, in setup_read_write
    self.data_provider.open("r+b")
  File "C:\travail\tmp\las\lib\site-packages\laspy\base.py", line 30, in open
    raise LaspyException("Error opening file")
laspy.util.LaspyException: Error opening file
```

Does anyone have a clue why the external opening does not work ? (I have not got a clue...)

Thanks !

**Comment by kalbermattenm** [comment]
Oh.... I forgot to specify that I am using the laspy pypi package (version 1.2.5), which was released in 2012...

**Comment by kalbermattenm** [comment]
Alright... this is actually working if I use the code from the master branch... (thus not an issue...)

Would it be possible to publish a new package to pypi ? (which is quite useful when using virtual environments...)

**Comment by KAMI911** [comment]
You probably can use
pip install https://github.com/grantbrown/laspy/archive/master.zip

**Comment by kalbermattenm** [comment]
Yes... I know... but it is to be used through buildout (https://github.com/sitn/las_extractor)... I might write some specific install code for it, but it would be so simpler to have an more up-to-date pypi release...

Thanks for your answer ;-)

**Comment by grantbrown** [comment]
Yes, we're overdue for a new pypi release and version bump. I'll look into it this morning.

**Comment by kalbermattenm** [comment]
That's great news ! Thanks a lot !

**Comment by grantbrown** [comment]
No problem, it was quite overdue given all of the bugfixes which have been made since the last release. It should be [updated](https://pypi.python.org/pypi?:action=display&name=laspy&version=1.3.0) now, let me know if you continue to experience any issues.
