### ISSUE TITLE
pip install laspy fails (v 1.3.0)

### ISSUE THREAD

**Issue by atph** [grantbrown/laspy#38]
Hey guys, 
Just a heads up, I ran into this issue while trying to install 1.3.0 via pip...
(on windows 8.1, using python 2.7.11  64 bit )   

<pre>pip install laspy
Collecting laspy
  Using cached laspy-1.3.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "c:\users\andrew~1.hew\appdata\local\temp\pip-build-tlkoee\laspy\setup.py", line 28, in <module>
        shutil.copyfile("laspytest/data/simple.laz", "simple.laz")
      File "c:\python27-64\lib\shutil.py", line 82, in copyfile
        with open(src, 'rb') as fsrc:
    IOError: [Errno 2] No such file or directory: 'laspytest/data/simple.laz'
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\andrew~1.hew\appdata\local\temp\pip-build-tlkoee\laspy</pre>

Using version 1.2.5 installs fine...
<pre>pip install laspy==1.2.5
Collecting laspy==1.2.5
  Using cached laspy-1.2.5.tar.gz
Requirement already satisfied (use --upgrade to upgrade): numpy in c:\python27-64\lib\site-packages (from laspy==1.2.5)
Installing collected packages: laspy
  Running setup.py install for laspy
Successfully installed laspy-1.2.5</pre>

**Comment by grantbrown** [comment]
Sorry about that, fixed in [1.3.2](https://pypi.python.org/pypi/laspy/1.3.2).
