### ISSUE TITLE
Memory leak - unreachable references to reader

### ISSUE THREAD

**Issue by silyko** [grantbrown/laspy#47]
Hi,

 I am seeing some memory leaks. Have not debugged it fully, but I believe it's due to objects keeping a reference to a base.FileManager object (file.File._reader). E.g. reader.header will hold a reference to reader. When reader is set to None in file.File.close, there will still be unreachable references to reader.
This amounts to some memory, e.g. when reader.point_refs is a really long list.
Problem can be reproduced with something like:

```python
import sys
import gc
import laspy.file as lasf
gc.set_debug(gc.DEBUG_LEAK)
plas = lasf.File(sys.argv[1])
p = plas.points
del p
print gc.collect()  # No unreachable objects yet
plas.close()
del plas
print gc.collect() # A lot of unreachable objects

**Comment by silyko** [comment]
An easy fix would be to just delete the objects, that holds these references in the Reader.close method...

**Comment by silyko** [comment]
I'll try to prepare a pull request. Would also be nice to avoid creating FileManager.point_refs until absolutely necessary. E.g. when memory mapping a las file with 500 million points, it takes a long time, and a lot of memory to generate this list. Will see if I can handle that somehow.

**Comment by silyko** [comment]
Correction: 
The circular references do seem to be collectable (no __del__ method). However the garbage collector does seem to be a bit slow in doing this... So no worries :-)

**Comment by grantbrown** [comment]
Sorry for the delayed reply, glad you got it figured out. The del methods which were previously included were actually *causing* a lot of the previous problems, as they overloaded the default destructors.

**Comment by silyko** [comment]
No problem :-) Yes - as I understand it, del methods will prevent automatic garbage collection of unreachable objects. Now they should be collected, eventually...

 I have fiddled a little with helping the garbage collector by deleting objects with circular references in the Reader / Write close methods. And also trying to avoid the call to build_point_refs in FileManager.get_points, which will construct a long list using which does not seem to be used. Might open a pull request.
